// Test generated by RoostGPT for test go-unit-algo-string using AI Type Open AI and AI Model gpt-4

package IsPowerOfTwo

import (
	"testing"
)

func TestIsPowerOfTwoBitwise_e8104160a5(t *testing.T) {
	testCases := []struct {
		num      int
		expected bool
	}{
		{num: 16, expected: true},
		{num: 18, expected: false},
		{num: 1, expected: true},
		{num: 0, expected: true},
		{num: -1, expected: false},
	}

	for _, tc := range testCases {
		result := isPowerOfTwoBitwise(tc.num)
		if result != tc.expected {
			t.Errorf("For number %d, expected %v but got %v", tc.num, tc.expected, result)
		} else {
			t.Logf("Success: For number %d, expected %v and got %v", tc.num, tc.expected, result)
		}
	}
}
