// Test generated by RoostGPT for test go-unit-algo-string using AI Type Open AI and AI Model gpt-4

package Fibonacci

import (
	"testing"
)

func TestFibonacci_3c2494e9fa(t *testing.T) {
	testCases := []struct {
		name     string
		input    int
		expected int
	}{
		{
			name:     "Test Case 1: Fibonacci of 5",
			input:    5,
			expected: 5,
		},
		{
			name:     "Test Case 2: Fibonacci of 10",
			input:    10,
			expected: 55,
		},
		{
			name:     "Test Case 3: Fibonacci of 0",
			input:    0,
			expected: 0,
		},
		{
			name:     "Test Case 4: Fibonacci of negative number",
			input:    -5,
			expected: 0,
		},
	}

	for _, tc := range testCases {
		t.Run(tc.name, func(t *testing.T) {
			result := fibonacci(tc.input)

			if result != tc.expected {
				t.Errorf("fibonacci(%d) = %d; expected %d", tc.input, result, tc.expected)
			} else {
				t.Logf("Success: fibonacci(%d) = %d", tc.input, result)
			}
		})
	}
}
