// Test generated by RoostGPT for test go-unit-algo-string using AI Type Open AI and AI Model gpt-4

package Factorial

import (
	"testing"
)

func TestFactorial_c8838e8b35(t *testing.T) {
	testCases := []struct {
		num      int
		expected int
	}{
		{0, 1},
		{1, 1},
		{2, 2},
		{3, 6},
		{4, 24},
		{5, 120},
		{-1, 1}, // Factorial of negative numbers is not defined, but our function returns 1
	}

	for _, tc := range testCases {
		t.Run("", func(t *testing.T) {
			result := Factorial(tc.num)
			if result != tc.expected {
				t.Errorf("Factorial(%d) = %d; expected %d", tc.num, result, tc.expected)
			} else {
				t.Logf("Factorial(%d) = %d; test passed", tc.num, result)
			}
		})
	}
}
